version: "3.4"

services:
  metamindservice:
    image: metamindservice
    container_name: metamindservice
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010/api
      PORT: 8095
    ports:
      - 8095:8095
    networks:
      ioak-net:
        aliases:
          - metamindservice.docker

networks:
  ioak-net:
    name: ioak-network
